name: Generate profile summary cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: johnshields
          BRANCH_NAME: main
          UTC_OFFSET: "+00:00"
          THEME: github_dark
          AUTO_PUSH: false
          EXCLUDE: ""
          NAME: johnshields
      - name: Prune unused cards
        run: |
          rm -f profile-summary-card-output/README.md
          rm -f profile-summary-card-output/github_dark/README.md
          rm -f profile-summary-card-output/github_dark/1-repos-per-language.svg
          rm -f profile-summary-card-output/github_dark/2-most-commit-language.svg
          rm -f profile-summary-card-output/github_dark/3-stats.svg
          rm -f profile-summary-card-output/github_dark/4-productive-time.svg
      - name: Commit profile details card
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-summary-card-output/github_dark/0-profile-details.svg
          git diff --cached --quiet || git commit -m "chore: update GitHub contribution card"
          git push
